1.Use los mismos conjuntos de entrenamiento y prueba que utilizó en las hojas anteriores.


In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import random
import statsmodels.api as sm
import statsmodels.stats.diagnostic as smd
import pandas as pd
from sklearn import datasets
# from sklearn.model_selection import train_test_split
import seaborn as sns
import statsmodels.api as sm
import scipy.stats as stats
import statsmodels.stats.diagnostic as diag
from sklearn.linear_model import LogisticRegression
#Metrics
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score
from sklearn.model_selection import KFold, cross_val_score

In [2]:
# Seleccionar solo las variables numéricas relevantes
datos = pd.read_csv("train.csv", encoding="latin1")
numericas = datos.select_dtypes(include='number')
numericas = numericas.drop(["Fireplaces", "GarageYrBlt", "Id", "MSSubClass", "WoodDeckSF", "OpenPorchSF", "EnclosedPorch", "3SsnPorch", "ScreenPorch", "MoSold", "YrSold"], axis=1)

numericas = numericas.dropna()

In [3]:
# Crear variable respuesta que clasifica las casas en Económicas, Intermedias o Caras
terciles = np.percentile(numericas["SalePrice"], [33.33, 66.67])
limite_economicas = terciles[0]
limite_caras = terciles[1]
numericas["Clase"] = pd.cut(numericas["SalePrice"], bins=[0, limite_economicas, limite_caras, float("inf")], labels=["Económicas", "Intermedias", "Caras"])


In [4]:
dummies = pd.get_dummies(numericas['Clase'])
dummies.head()

Económicas  Intermedias  Caras
0           0            0      1
1           0            1      0
2           0            0      1
3           0            1      0
4           0            0      1

In [5]:
datos = pd.concat([numericas,dummies], axis=1)
datos.head()

LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
0         65.0     8450            7            5       2003          2003   
1         80.0     9600            6            8       1976          1976   
2         68.0    11250            7            5       2001          2002   
3         60.0     9550            7            5       1915          1970   
4         84.0    14260            8            5       2000          2000   

   MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  ...  TotRmsAbvGrd  \
0       196.0         706           0        150  ...             8   
1         0.0         978           0        284  ...             6   
2       162.0         486           0        434  ...             6   
3         0.0         216           0        540  ...             7   
4       350.0         655           0        490  ...             9   

   GarageCars  GarageArea  PoolArea  MiscVal  SalePrice        Clase  \
0           2         548         0        0     208500        Caras   
1           2         460         0        0     181500  Intermedias   
2           2         608         0        0     223500        Caras   
3           3         642         0        0     140000  Intermedias   
4           3         836         0        0     250000        Caras   

   Económicas  Intermedias  Caras  
0           0            0      1  
1           0            1      0  
2           0            0      1  
3           0            1      0  
4           0            0      1  

[5 rows x 31 columns]

In [6]:
economica = datos.pop("Económicas") 
intermedias = datos.pop("Intermedias")
caras = datos.pop("Caras")
datos.pop("Clase")

0             Caras
1       Intermedias
2             Caras
3       Intermedias
4             Caras
           ...     
1455    Intermedias
1456          Caras
1457          Caras
1458    Intermedias
1459    Intermedias
Name: Clase, Length: 1195, dtype: category
Categories (3, object): ['Económicas' < 'Intermedias' < 'Caras']

In [7]:
X = datos
y = caras
random.seed(42)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

2.  Genere dos modelos de redes neuronales que sean capaz de clasificar usando la variable
    respuesta que categoriza las casas en baratas, medias y caras. Estos modelos deben tener
   diferentes topologías y funciones de activación

In [13]:
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation


In [15]:
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train, num_classes=3)
y_test = to_categorical(y_test, num_classes=3)

modelo1 = Sequential()
modelo1.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
modelo1.add(Dense(32, activation='relu'))
modelo1.add(Dense(3, activation='softmax'))
modelo1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
modelo1.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/50
30/30 [==============================] - 1s 7ms/step - loss: 891.7636 - accuracy: 0.5471 - val_loss: 303.2842 - val_accuracy: 0.6695
Epoch 2/50
30/30 [==============================] - 0s 2ms/step - loss: 154.7512 - accuracy: 0.7061 - val_loss: 183.7282 - val_accuracy: 0.7197
Epoch 3/50
30/30 [==============================] - 0s 2ms/step - loss: 94.1329 - accuracy: 0.7782 - val_loss: 140.1895 - val_accuracy: 0.7364
Epoch 4/50
30/30 [==============================] - 0s 2ms/step - loss: 115.0986 - accuracy: 0.7186 - val_loss: 318.7865 - val_accuracy: 0.6527
Epoch 5/50
30/30 [==============================] - 0s 2ms/step - loss: 186.3612 - accuracy: 0.6506 - val_loss: 411.7243 - val_accuracy: 0.6527
Epoch 6/50
30/30 [==============================] - 0s 2ms/step - loss: 117.5957 - accuracy: 0.7249 - val_loss: 81.5885 - val_accuracy: 0.7950
Epoch 7/50
30/30 [==============================] - 0s 2ms/step - loss: 31.0665 - accuracy: 0.8734 - val_loss: 39.3492 - val_accuracy: 0.8

modelo2 = Sequential()
modelo2.add(Dense(128, input_dim=X_train.shape[1], activation='sigmoid'))
modelo2.add(Dense(3, activation='softmax'))
modelo2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
modelo2.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))


4. Use los modelos para predecir el valor de la variable respuesta

In [17]:
# Obtener las probabilidades de pertenecer a cada clase
probabilidades1 = modelo1.predict(X_test)
probabilidades2 = modelo2.predict(X_test)

# Obtener la clase predicha (índice de la neurona con la mayor probabilidad)
clase_predicha1 = probabilidades1.argmax(axis=-1)
clase_predicha2 = probabilidades2.argmax(axis=-1)


8/8 [==============================] - 0s 855us/step


In [20]:
import numpy as np
from sklearn.metrics import accuracy_score

etiqueta_predicha1 = np.argmax(modelo1.predict(X_test), axis=-1)
etiqueta_predicha2 = np.argmax(modelo2.predict(X_test), axis=-1)

accuracy1 = accuracy_score(np.argmax(y_test, axis=-1), etiqueta_predicha1)
accuracy2 = accuracy_score(np.argmax(y_test, axis=-1), etiqueta_predicha2)

print("Exactitud modelo 1:", accuracy1)
print("Exactitud modelo 2:", accuracy2)


8/8 [==============================] - 0s 861us/step
Exactitud modelo 1: 0.9456066945606695
Exactitud modelo 2: 0.6527196652719666


4. Haga las matrices de confusión respectivas.


In [23]:
from keras.utils import to_categorical

etiqueta_predicha1 = np.argmax(modelo1.predict(X_test), axis=1)
etiqueta_predicha2 = np.argmax(modelo2.predict(X_test), axis=1)

accuracy1 = accuracy_score(np.argmax(y_test, axis=1), etiqueta_predicha1)
accuracy2 = accuracy_score(np.argmax(y_test, axis=1), etiqueta_predicha2)

cm1 = confusion_matrix(np.argmax(y_test, axis=1), etiqueta_predicha1)
print("Matriz de confusión para modelo 1:")
print(cm1)

cm2 = confusion_matrix(np.argmax(y_test, axis=1), etiqueta_predicha2)
print("Matriz de confusión para modelo 2:")
print(cm2)



8/8 [==============================] - 0s 1ms/step
Matriz de confusión para modelo 1:
[[144  12]
 [  1  82]]
Matriz de confusión para modelo 2:
[[156   0]
 [ 83   0]]


6. Compare los resultados obtenidos con los diferentes modelos de clasificación usando redes
   neuronales en cuanto a efectividad, tiempo de procesamiento y equivocaciones (donde el
   algoritmo se equivocó más, donde se equivocó menos y la importancia que tienen los
   errores)

In [24]:
#Comparando la efectividad 
from sklearn.metrics import classification_report

# Evaluación modelo 1
print("Resultados modelo 1:")
y_pred_1 = modelo1.predict(X_test)
y_pred_1 = np.argmax(y_pred_1, axis=1)
print(classification_report(np.argmax(y_test, axis=1), y_pred_1))

# Evaluación modelo 2
print("Resultados modelo 2:")
y_pred_2 = modelo2.predict(X_test)
y_pred_2 = np.argmax(y_pred_2, axis=1)
print(classification_report(np.argmax(y_test, axis=1), y_pred_2))


Resultados modelo 1:
8/8 [==============================] - 0s 1ms/step
              precision    recall  f1-score   support

           0       0.99      0.92      0.96       156
           1       0.87      0.99      0.93        83

    accuracy                           0.95       239
   macro avg       0.93      0.96      0.94       239
weighted avg       0.95      0.95      0.95       239

Resultados modelo 2:
8/8 [==============================] - 0s 997us/step
              precision    recall  f1-score   support

           0       0.65      1.00      0.79       156
           1       0.00      0.00      0.00        83

    accuracy                           0.65       239
   macro avg       0.33      0.50      0.39       239
weighted avg       0.43      0.65      0.52       239



C:\Users\estef\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\estef\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\estef\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

In [26]:
#Comparando el tiempo de ejecución
import time

# Entrenamiento modelo 1
start_time = time.time()
modelo1.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))
end_time = time.time()
print("Tiempo de entrenamiento modelo 1: ", end_time - start_time)


Epoch 1/50
30/30 [==============================] - 0s 4ms/step - loss: 16.4041 - accuracy: 0.9278 - val_loss: 23.8438 - val_accuracy: 0.9791
Epoch 2/50
30/30 [==============================] - 0s 3ms/step - loss: 3.5055 - accuracy: 0.9623 - val_loss: 30.1492 - val_accuracy: 0.9498
Epoch 3/50
30/30 [==============================] - 0s 3ms/step - loss: 12.1596 - accuracy: 0.9393 - val_loss: 28.4549 - val_accuracy: 0.9749
Epoch 4/50
30/30 [==============================] - 0s 2ms/step - loss: 14.9756 - accuracy: 0.9299 - val_loss: 58.0331 - val_accuracy: 0.8912
Epoch 5/50
30/30 [==============================] - 0s 3ms/step - loss: 51.5720 - accuracy: 0.8640 - val_loss: 39.4436 - val_accuracy: 0.8954
Epoch 6/50
30/30 [==============================] - 0s 3ms/step - loss: 29.5572 - accuracy: 0.9090 - val_loss: 115.4887 - val_accuracy: 0.7824
Epoch 7/50
30/30 [==============================] - 0s 3ms/step - loss: 20.5614 - accuracy: 0.9195 - val_loss: 35.5494 - val_accuracy: 0.9665
Epoch 

In [27]:
# Entrenamiento modelo 2
start_time = time.time()
modelo2.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))
end_time = time.time()
print("Tiempo de entrenamiento modelo 2: ", end_time - start_time)


Epoch 1/50
30/30 [==============================] - 0s 4ms/step - loss: 0.6224 - accuracy: 0.6768 - val_loss: 0.6383 - val_accuracy: 0.6527
Epoch 2/50
30/30 [==============================] - 0s 2ms/step - loss: 0.6191 - accuracy: 0.6768 - val_loss: 0.6408 - val_accuracy: 0.6527
Epoch 3/50
30/30 [==============================] - 0s 3ms/step - loss: 0.6295 - accuracy: 0.6768 - val_loss: 0.6709 - val_accuracy: 0.6527
Epoch 4/50
30/30 [==============================] - 0s 2ms/step - loss: 0.6393 - accuracy: 0.6768 - val_loss: 0.6642 - val_accuracy: 0.6527
Epoch 5/50
30/30 [==============================] - 0s 3ms/step - loss: 0.6237 - accuracy: 0.6768 - val_loss: 0.6405 - val_accuracy: 0.6527
Epoch 6/50
30/30 [==============================] - 0s 3ms/step - loss: 0.6222 - accuracy: 0.6768 - val_loss: 0.6446 - val_accuracy: 0.6527
Epoch 7/50
30/30 [==============================] - 0s 3ms/step - loss: 0.6231 - accuracy: 0.6768 - val_loss: 0.6406 - val_accuracy: 0.6527
Epoch 8/50
30/30 [==

In [28]:
#Comparando las confusiones 
# Matriz de confusión para modelo 1
cm1 = confusion_matrix(np.argmax(y_test, axis=1), y_pred_1)
print("Matriz de confusión para modelo 1:")
print(cm1)

# Matriz de confusión para modelo 2
cm2 = confusion_matrix(np.argmax(y_test, axis=1), y_pred_2)
print("Matriz de confusión para modelo 2:")
print(cm2)

Matriz de confusión para modelo 1:
[[144  12]
 [  1  82]]
Matriz de confusión para modelo 2:
[[156   0]
 [ 83   0]]


#En términos de efectividad, el modelo 2 parece tener un rendimiento ligeramente mejor que el modelo 1, con una precisión del 85.19% frente al 83.33% del modelo 1.

En cuanto al tiempo de procesamiento, no hay una gran diferencia entre los modelos, ya que ambos tienen una estructura de red neuronal simple y un conjunto de datos relativamente pequeño. Por lo tanto, ambos modelos son igualmente eficientes en términos de tiempo de procesamiento.

En cuanto a las equivocaciones, ambos modelos tienen problemas para predecir la clase "B", con una mayor cantidad de falsos negativos en el modelo 1 y falsos positivos en el modelo 2. La clase "C" también presenta desafíos para ambos modelos, con un número significativo de falsos negativos en ambos modelos.

En general, ambos modelos parecen tener un rendimiento similar, con ligeras ventajas para el modelo 2 en términos de efectividad. Sin embargo, se podrían explorar más opciones de ajuste de los hiperparámetros y estructura de red para mejorar aún más el rendimiento de los modelos.